

from pathlib import Path
from types import SimpleNamespace

import pandas as pd
import torch
import yaml
from torch.utils.data import Dataset


REQUIRED_KEYS = [
    "T", "in_dim",
    "d_model", "n_heads", "n_layers", "d_ff", "dropout",
    "d_z",
    "d_dec_hidden",
    "batch_size",
    "lr", "weight_decay", "grad_clip",
    "n_epochs",
    "device", "seed",
    "data_path",
    "price_cols_prefix", "prob_cols_prefix",
]


def load_config(path: str) -> SimpleNamespace:
    with open(path) as f:
        raw = yaml.safe_load(f)

    expected = set(REQUIRED_KEYS)
    missing = expected - raw.keys()
    extra = raw.keys() - expected
    if missing:
        raise KeyError(f"config missing keys: {sorted(missing)}")
    if extra:
        raise KeyError(f"config has unknown keys: {sorted(extra)}")

    cfg = SimpleNamespace(**raw)

    if cfg.device == "auto":
        cfg.device = "cuda" if torch.cuda.is_available() else "cpu"

    return cfg


class PriceDataset(Dataset):
    """One row per training example. Each row has T+1 prices and T+1 true
    probabilities (soft targets, in [0,1]) generated by the simulator.

    Columns expected:
      <price_cols_prefix>0, <price_cols_prefix>1, ..., <price_cols_prefix>T
      <prob_cols_prefix>0,  <prob_cols_prefix>1,  ..., <prob_cols_prefix>T

    Each item is a tuple (prices, true_probs):
      prices:     (T+1,) float
      true_probs: (T+1,) float, soft targets in [0,1]
    """

    def __init__(self, csv_path: str, T: int,
                 price_cols_prefix: str = "price_",
                 prob_cols_prefix: str = "prob_"):
        path = Path(csv_path)
        if not path.exists():
            raise FileNotFoundError(f"CSV not found: {path.resolve()}")

        df = pd.read_csv(path)

        price_cols = [f"{price_cols_prefix}{i}" for i in range(T + 1)]
        prob_cols = [f"{prob_cols_prefix}{i}" for i in range(T + 1)]

        missing = [c for c in price_cols + prob_cols if c not in df.columns]
        if missing:
            raise KeyError(f"CSV missing columns: {missing}")

        self.prices = torch.tensor(df[price_cols].values, dtype=torch.float32)
        self.true_probs = torch.tensor(df[prob_cols].values, dtype=torch.float32)

    def __len__(self):
        return self.prices.shape[0]

    def __getitem__(self, i):
        return self.prices[i], self.true_probs[i]
